name: Publish

on:
  workflow_run:
    workflows: ['Test']
    branches: [main]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: git fetch --prune --unshallow
    - name: Set up PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pdm install

    - name: Build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: pdm run ./scripts/publish.sh

    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
          password: ${{ secrets.PYPI_TOKEN }}

    - name: Tag
      run: |
        git push
        git push --tags
