name: Tag

on:
  workflow_run:
    workflows: ['Test']
    branches: [main]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: git fetch --prune --unshallow
    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pdm install

    - name: Build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: pdm run ./scripts/publish.sh

    - name: Tag
      run: |
        git push
        git push --tags
